[package]
name = "rustyms"
version = "0.6.1"
edition = "2021"
license = "MIT"
authors = ["Douwe Schulte <d.schulte@uu.nl>"]
description = "A library to match spectra to peptides."
categories = ["science"]
keywords = ["spectra", "massspectrometry", "ms", "fragmentation", "proforma"]
repository = "https://github.com/snijderlab/rustyms"
readme = "README.md"
include = ["src/**/*", "databases/**/*", "LICENSE", "README.md", "build.rs"]
rust-version = "1.70.0"

[dependencies]
bincode = "1.3"
flate2 = "1.0"
itertools = "0.12"
regex = "1.8"
serde = { version = "1.0", features = ["derive"] }
statrs = "0.16"
uom = { version = "0.35", features = ["use_serde"] }

[build-dependencies]
bincode = "1.3"
flate2 = "1.0"
itertools = "0.12"
regex = "1.8"
serde = { version = "1.0", features = ["derive"] }
uom = { version = "0.35", features = ["use_serde"] }
