[package]
name = "rustyms"
version = "0.7.0"
edition = "2021"
license = "MIT"
authors = ["Douwe Schulte <d.schulte@uu.nl>"]
description = "A library to handle proteomic mass spectrometry data and match peptides to spectra."
categories = ["science"]
keywords = ["spectra", "massspectrometry", "bio", "fragmentation", "proforma"]
repository = "https://github.com/snijderlab/rustyms"
readme = "README.md"
include = ["src/**/*", "databases/**/*", "LICENSE", "README.md", "build.rs"]
rust-version = "1.70.0"

[dependencies]
bincode = "1.3"
flate2 = "1.0"
itertools = "0.12"
regex = "1.8"
serde = { version = "1.0", features = ["derive"] }
probability = "0.20"
uom = { version = "0.35", features = ["use_serde"] }

[build-dependencies]
bincode = "1.3"
flate2 = "1.0"
itertools = "0.12"
regex = "1.8"
serde = { version = "1.0", features = ["derive"] }
uom = { version = "0.35", features = ["use_serde"] }
