[package]
name = "rustyms"
version = "0.5.0"
edition = "2021"
license = "MIT"
authors = ["Douwe Schulte <d.schulte@uu.nl>"]
description = "A library to match spectra to peptides."
categories = ["science"]
keywords = ["spectra", "massspectrometry", "ms", "fragmentation", "proforma"]
repository = "https://github.com/snijderlab/rustyms"
readme = "README.md"
include = ["src/**/*", "databases/**/*", "LICENSE", "README.md", "build.rs"]
rust-version = "1.62.1"

[dependencies]
uom = "0.35"
statrs = "0.16"
serde = { version = "1.0", features = ["derive"] }
regex = "1.8"
itertools = "0.11"
flate2 = "1.0"
terminal_size = "0.3"

[build-dependencies]
regex = "1.8"
flate2 = "1.0"
serde = { version = "1.0", features = ["derive"] }
terminal_size = "0.3"
