[package]
name = "rustyms"
version = "0.1.1"
edition = "2021"
license = "MIT"
authors = ["Douwe Schulte <d.schulte@uu.nl>"]
description = "A library to match spectra to peptides."
repository = "https://github.com/snijderlab/rustyms"
readme = "README.md"
include = ["src/**/*", "LICENSE", "README.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uom = "0.34"
entab="0.3"
statrs = "0.16"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
regex = "1.8"