[package]
name = "rustyms_py"
version = "0.7.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rustyms_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
rustyms = "0.7.0"
