[package]
name = "rustyms"
version = "0.7.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Douwe Schulte <d.schulte@uu.nl>"]
description = "A library to handle proteomic mass spectrometry data and match peptides to spectra."
categories = ["science"]
keywords = ["spectra", "massspectrometry", "bio", "fragmentation", "proforma"]
repository = "https://github.com/snijderlab/rustyms"
readme = "README.md"
include = ["src/**/*", "databases/**/*", "LICENSE", "README.md", "build.rs"]
rust-version = "1.70.0"

[dependencies]
rustyms-core = { path = "../rustyms-core" }
rustyms-imgt = { path = "../rustyms-imgt", optional = true, default-features = false }
rustyms-align = { path = "../rustyms-align", optional = true, default-features = false }
rustyms-identification = { path = "../rustyms-identification", optional = true }

[features]
default = ["rayon", "imgt", "align", "identification", "consecutive-align"]

# These are to make sure everything dances together in harmony
rayon = ["rustyms-imgt/rayon", "rustyms-align/rayon"]
align = ["rustyms-align"]
imgt = ["rustyms-imgt"]
identification = ["rustyms-identification"]
consecutive-align = [
    "rustyms-align/rustyms-imgt",
    "rustyms-align",
    "rustyms-imgt",
]
