[package]
name = "rustyms"
version = "0.8.3"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Douwe Schulte <d.schulte@uu.nl>"]
description = "A library to handle proteomic mass spectrometry data and match peptides to spectra."
categories = ["science::bio"]
keywords = ["spectra", "mass-spectrometry", "bio", "fragmentation", "proforma"]
repository = "https://github.com/snijderlab/rustyms"
readme = "README.md"
include = [
    "src/**/*",
    "databases/**/*",
    "README.md",
    "build.rs",
    "benches/**/*",
]
rust-version = "1.70.0"

[dependencies]
bincode = "1.3"
flate2 = "1.0"
itertools = "0.13"
ordered-float = { version = "4.2", features = ["serde"] }
probability = { version = "0.20", optional = true }
rayon = { version = "1.9", optional = true }
regex = "1.8"
serde = { version = "1.0", features = ["derive", "rc"] }
similar = "2.4"
uom = { version = "0.36", features = ["use_serde", "usize", "isize"] }
ndarray = { version = "0.15", optional = true }
rand = { version = "0.8.5", optional = true }

[build-dependencies]
bincode = "1.3"
flate2 = "1.0"
itertools = "0.13"
ordered-float = { version = "4.2", features = ["serde"] }
regex = "1.8"
serde = { version = "1.0", features = ["derive", "rc"] }
uom = { version = "0.36", features = ["use_serde", "usize", "isize"] }
roxmltree = "0.20"

[dev-dependencies]
iai-callgrind = "0.11.0"
serde_json = "1.0"

[features]
default = ["imgt", "align", "identification", "rayon", "isotopes", "rand"]
imgt = []
align = []
identification = []
isotopes = ["probability", "ndarray"]

[[bench]]
name = "iai"
harness = false
