version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
    rust: "latest"

python:
  install:
    - method: pip
      path: rustyms-py
      extra_requirements:
        - docs

sphinx:
  builder: dirhtml
